In [13]:
import pandas as pd

In [14]:
target_uni_lst = [
"Algoma University",
"University of Toronto",
"Carleton University",
"Dominican University College/Collège Universitaire Dominicain",
"Lakehead University",
"Laurentian University of Sudbury/Université Laurentienne de Sudbury",
"McMaster University",
"Nipissing University",
"University of Ottawa",
"Saint Paul University",
"Queen's University",
"Ryerson University",
"Trent University",
"Western University",
"Wilfrid Laurier University",
"University of Windsor",
"York University",
"Ontario College of Art and Design University",
"University of Ontario Institute of Technology",
"Université de Hearst",
"Huntington University",
"University of British Columbia",
"Simon Fraser University",
"University of Victoria",
"University of Calgary",
"University of Alberta",
"McGill University",
"Université de Montréal",
"Université Laval",
"Université de Sherbrooke",
"Concordia University",
"Dalhousie University",
"Memorial University of Newfoundland",
"University of Manitoba",
"University of Saskatchewan",
"University of Regina",
"University of New Brunswick",
"St. Francis Xavier University",
"Mount Allison University",
"University of Prince Edward Island",
]

In [15]:
for i in target_uni_lst:
    print(i, sep="\n")

Algoma University
University of Toronto
Carleton University
Dominican University College/Collège Universitaire Dominicain
Lakehead University
Laurentian University of Sudbury/Université Laurentienne de Sudbury
McMaster University
Nipissing University
University of Ottawa
Saint Paul University
Queen's University
Ryerson University
Trent University
Western University
Wilfrid Laurier University
University of Windsor
York University
Ontario College of Art and Design University
University of Ontario Institute of Technology
Université de Hearst
Huntington University
University of British Columbia
Simon Fraser University
University of Victoria
University of Calgary
University of Alberta
McGill University
Université de Montréal
Université Laval
Université de Sherbrooke
Concordia University
Dalhousie University
Memorial University of Newfoundland
University of Manitoba
University of Saskatchewan
University of Regina
University of New Brunswick
St. Francis Xavier University
Mount Allison University
University of Prince Edward Island

In [16]:
canada_df = pd.read_csv("~/Uforse/university_crawl/university_info_generator/fetch_logic/filter_logic/all_universities_canada_info.csv")

In [17]:
canada_df.head()

,index,id_,university_name,abbreviation,website,wikipedia,university_type,graduation_year,location,graduation_rate,...,ranking_us_news_2023,ranking_times_rank_2024,ranking_arwu_rank_2023,important_calendar,statistics,popular_programs,programs,faculty,characteristics,others
0,Algoma University,71,Algoma University,Algoma U,https://www.algomau.ca,https://en.wikipedia.org/wiki/Algoma_University,Public University,4,"Sault Ste. Marie, Ontario, Canada\nBrampton, O...",55%,...,NaN,NaN,NaN,https://algomau.ca/calendar/,Undergraduate Programs: 30\nMaster's Programs:...,Master of Computer Science,Master of Computer Science\nArts\nScience\nBus...,Faculty of Business and Economics\nBiology\nCo...,Algoma University is characterized by its stro...,NaN
1,University of Toronto,49,University of Toronto,U of T,https://www.utoronto.ca,https://en.wikipedia.org/wiki/University_of_To...,Public University,4,"Toronto, Ontario, Canada\nMississauga, Ontario...",89%,...,18.0,21,24,https://artsci.calendar.utoronto.ca/,Undergraduate Programs: 700\nMaster's Programs...,Education Program\nSauder Business School\nEng...,Aboriginal Studies\nAccounting (B.Com)\nActuar...,"Applied Science and Engineering\nArchitecture,...",The University of Toronto is recognized global...,NaN
2,University of Calgary,92,University of Calgary,UCalgary,https://www.ucalgary.ca,https://en.wikipedia.org/wiki/University_of_Ca...,Public University,4,"Calgary, Alberta, Canada\nDoha, Ad-Dawhah, Qatar",89%,...,175.0,201–250,201-300,https://calendar.ucalgary.ca/acadsched,Undergraduate Programs: 99\nMaster's Programs:...,Hospitality and Leisure Management\nNursing\nS...,Accounting\nActuarial Science\nAncient and Med...,Cumming School of Medicine\nFaculty of Arts\nF...,The University of Calgary is known for its div...,NaN
3,Memorial University of Newfoundland,1,Memorial University of Newfoundland,MUN,https://www.mun.ca,https://en.wikipedia.org/wiki/Memorial_Univers...,Public University,4,"St. John's, Newfoundland and Labrador, Canada\...",89%,...,NaN,501–600,701-800,https://www.mun.ca/regoff/calendar/,Undergraduate Programs: More than 100 \nMaste...,Medicine Program\nEngineering Program,Master of Applied Ocean Technology (Ocean Mapp...,Faculty of Business Administration\nFaculty of...,Memorial University of Newfoundland is recogni...,NaN
4,University of Prince Edward Island,2,University of Prince Edward Island,UPEI,https://www.upei.ca,https://en.wikipedia.org/wiki/University_of_Pr...,Public University,4,"Charlottetown, Prince Edward Island, Canada",89%,...,NaN,NaN,NaN,https://www.upei.ca/registrar/calendar-dates,Undergraduate Programs: 99\nMaster's and PhD P...,Veterinary Medicine\nBusiness\nNursing,Bachelor of Science in Nursing\nMaster of Educ...,"Biology, Faculty of \nSustainable Design Engi...",The University of Prince Edward Island (UPEI) ...,NaN

In [18]:
filtered_df = canada_df[canada_df['university_name'].isin(target_uni_lst)]

In [23]:
filtered_df.to_csv("all_universities_canada_info_filtered.csv", index=False)

In [24]:
filtered_df.head()

,index,id_,university_name,abbreviation,website,wikipedia,university_type,graduation_year,location,graduation_rate,...,ranking_us_news_2023,ranking_times_rank_2024,ranking_arwu_rank_2023,important_calendar,statistics,popular_programs,programs,faculty,characteristics,others
0,Algoma University,71,Algoma University,Algoma U,https://www.algomau.ca,https://en.wikipedia.org/wiki/Algoma_University,Public University,4,"Sault Ste. Marie, Ontario, Canada\nBrampton, O...",55%,...,NaN,NaN,NaN,https://algomau.ca/calendar/,Undergraduate Programs: 30\nMaster's Programs:...,Master of Computer Science,Master of Computer Science\nArts\nScience\nBus...,Faculty of Business and Economics\nBiology\nCo...,Algoma University is characterized by its stro...,NaN
1,University of Toronto,49,University of Toronto,U of T,https://www.utoronto.ca,https://en.wikipedia.org/wiki/University_of_To...,Public University,4,"Toronto, Ontario, Canada\nMississauga, Ontario...",89%,...,18.0,21,24,https://artsci.calendar.utoronto.ca/,Undergraduate Programs: 700\nMaster's Programs...,Education Program\nSauder Business School\nEng...,Aboriginal Studies\nAccounting (B.Com)\nActuar...,"Applied Science and Engineering\nArchitecture,...",The University of Toronto is recognized global...,NaN
2,University of Calgary,92,University of Calgary,UCalgary,https://www.ucalgary.ca,https://en.wikipedia.org/wiki/University_of_Ca...,Public University,4,"Calgary, Alberta, Canada\nDoha, Ad-Dawhah, Qatar",89%,...,175.0,201–250,201-300,https://calendar.ucalgary.ca/acadsched,Undergraduate Programs: 99\nMaster's Programs:...,Hospitality and Leisure Management\nNursing\nS...,Accounting\nActuarial Science\nAncient and Med...,Cumming School of Medicine\nFaculty of Arts\nF...,The University of Calgary is known for its div...,NaN
3,Memorial University of Newfoundland,1,Memorial University of Newfoundland,MUN,https://www.mun.ca,https://en.wikipedia.org/wiki/Memorial_Univers...,Public University,4,"St. John's, Newfoundland and Labrador, Canada\...",89%,...,NaN,501–600,701-800,https://www.mun.ca/regoff/calendar/,Undergraduate Programs: More than 100 \nMaste...,Medicine Program\nEngineering Program,Master of Applied Ocean Technology (Ocean Mapp...,Faculty of Business Administration\nFaculty of...,Memorial University of Newfoundland is recogni...,NaN
4,University of Prince Edward Island,2,University of Prince Edward Island,UPEI,https://www.upei.ca,https://en.wikipedia.org/wiki/University_of_Pr...,Public University,4,"Charlottetown, Prince Edward Island, Canada",89%,...,NaN,NaN,NaN,https://www.upei.ca/registrar/calendar-dates,Undergraduate Programs: 99\nMaster's and PhD P...,Veterinary Medicine\nBusiness\nNursing,Bachelor of Science in Nursing\nMaster of Educ...,"Biology, Faculty of \nSustainable Design Engi...",The University of Prince Edward Island (UPEI) ...,NaN

In [20]:
print(len(filtered_df.index))

39